[workspace]

members = ["projects/*"]
default-members = [
    "projects/crypto-aaencode",
    "projects/crypto-marysue",
    "projects/crypto-invert",
    "projects/crypto-random-map",
    "projects/wasm-crypto-moe",
]

[profile.release]
lto = true
opt-level = "s"